### ISSUE TITLE
How to change /admin url?

### ISSUE THREAD

**Issue by AhnSeongHyun** [kaushikraj/sb-admin-2-flask-admin#2]
In the flask-admin, I change admin url using url argument of Admin(). 
But this example(sb-admin-2-flask-admin) do not change admin url. 

how to change /admin url?

``` python
    admin = admin.Admin(app,
                        'Test Admin',
                        index_view=AdminIndexView(),
                        url='/test')

```

**Comment by kaushikraj** [comment]
The URLs are defined in the views (https://github.com/kaushikraj/sb-admin-2-flask-admin/blob/master/views.py)

You can control them with @expose() for each method.
