### ISSUE TITLE
run.py and env not found

### ISSUE THREAD

**Issue by Mazuco** [kaushikraj/sb-admin-2-flask-admin#3]
When I try use this command:

$ virtaulenv env

and 

$python run.py

both files is not present in this project.

**Comment by kaushikraj** [comment]
have you installed python?

**Comment by xakraz** [comment]
@Mazuco if you are looking for the `run.py` as it is referenced in the blog post, it is actually `app.py`.

**Comment by kaushikraj** [comment]
Thanks a lot. Fixed the typo.
